### ISSUE TITLE
Player stacking in minimap, right clicking only shows one player

### ISSUE THREAD

**Issue by W1GZY** [TiboDeMunck/runelite-live-friend-locations-plugin#2]
When there is more player in the same direction you can only right click on the one that is on the top of the stack. This is not that bad when the icons are different, as in the images below but it is hard to differentiate when there is stack of the same icon.

![Screenshot_2](https://user-images.githubusercontent.com/96368352/147371959-4cde55b1-cab6-49f7-8d39-c240f7da9500.png)

2 players at the same direction but right click only shows one.
![Screenshot_3](https://user-images.githubusercontent.com/96368352/147371997-2dfa13fd-86c0-43cd-8860-eb062c23181f.jpg)

**Comment by TiboDeMunck** [comment]
That's sadly how the Runelite map features work. I have midterms right now but will look at it when that's over. 

For now my temporary "solution" would be to focus on the guy who is on top to then see where the other players are.
