### ISSUE TITLE
(Suggestion) Ability to share shooting star locations

### ISSUE THREAD

**Issue by W1GZY** [TiboDeMunck/runelite-live-friend-locations-plugin#5]
I have some friends that are doing group activities together like shooting star and I thought it would be really nice to able to mark the star landing zone in the world map when it is found automatically.

I have used the plugin "Impling finder" that does the same but for implings that works for it is purpose and would love to have star integrated with this plugin if possible. Would be cool to see which world the star is in when you right click it too

**Comment by TiboDeMunck** [comment]
Although I really like the idea, it doesn't fall under the scope of this plugin. 

I would try to propose this idea to the shooting star plugins that already exist.
