### ISSUE TITLE
Suggestion | Sharing a configurable icon

### ISSUE THREAD

**Issue by toxxicjtag** [TiboDeMunck/runelite-live-friend-locations-plugin#6]
We use this plugin as a community. A lot were talking about the fact that most are just bronze helmets and was wondering if an update could come out with more icons and passing that server side as well as location. 

A suggestion for icons to add: the new clan title icons. There's like 100 of them and they are pretty detailed for their size. I'm sure more could be used but that was just a quick thought for a bunch of familiar rank icons.

I know the plugin looks pretty...quiet, hope this gets checked out.

**Comment by toxxicjtag** [comment]
Oh wow, thanks for the response.

I got all the png files for the ranks from the wiki page. https://oldschool.runescape.wiki/w/Clan_Settings

**Comment by TiboDeMunck** [comment]
Okay so there are two options on toggle (only one will be implemented):
Option 1) You get special icons for people who are in your clan, people who are not in your clan will get the default account type icons.
Option 2) Everyone who uses the plugin on the same API server sees each others clan icons, even if you are in a different clan you will be able to see the title of someone in another clan.

My preference goes to the first option. Could you please discuss this with who you use this plugin with?

**Comment by toxxicjtag** [comment]
I just don't think the map will be as informative of who's around with a bunch of the same icon around and will have to hover over everyone, so my recommendation would be option 2.

Additionally, this would help with people who may have left and determining if another shared key needs to be released. Icons not used in the clan chat would stand out on the map. I know people can just hide but more for...keeping up with the people that come and go and not the people being malicious. 

But either way up to you.

**Comment by TiboDeMunck** [comment]
I've sort of done both, I would like to reiterate that the icons displayed on the map will be equal to the clan title you have. The API Server will have to be updated (fetch upstream in the fork).

I need to ask around if I can display a message in RuneLite to enlighten users who use this plugin to update the API server.

ps: the icons right now are very low quality due to resizing and would like to fix this before pushing changes.

**Comment by TiboDeMunck** [comment]
If you want to, you can update the API. This shouldn't have any impact on the current plugin version.

**Comment by toxxicjtag** [comment]
Updated it, just waiting for the plugin side. Thanks alot.
