### ISSUE TITLE
make a underground icon for players that are not in runescape surface

### ISSUE THREAD

**Issue by WiggleNibble** [TiboDeMunck/runelite-live-friend-locations-plugin#8]
make icons show up in an underground and or up when runescape surface is only shown.
![image](https://user-images.githubusercontent.com/110086391/185790770-8c36cab2-e9ce-4f8e-b9e7-fdb59b9abefd.png)

**Comment by TiboDeMunck** [comment]
Changes made, waiting on runelite to confirm changes
