### ISSUE TITLE
Error when trying to deploy app

### ISSUE THREAD

**Issue by 3st4ckz** [TiboDeMunck/runelite-live-friend-locations-plugin#9]
When I try to manually deploy the app on Heroku I get the following error in the logs:

`-----> Building on the Heroku-22 stack
-----> Using buildpack: heroku/gradle
-----> Gradle app detected
-----> Installing OpenJDK 1.8... done
-----> Building Gradle app...
-----> executing ./gradlew stage
       To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.6.1/userguide/gradle_daemon.html.
       Daemon will be stopped at the end of the build stopping after processing
       
       FAILURE: Build failed with an exception.
       
       * What went wrong:
       Task 'stage' not found in root project 'livelocationsharing'.
       
       * Try:
       Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
       
       * Get more help at https://help.gradle.org
       
       BUILD FAILED in 4s
 !     ERROR: Failed to run Gradle!
       It looks like your project does not contain a 'stage' task, which Heroku needs in order
       to build your app. Our Dev Center article on preparing a Gradle application for Heroku
       describes how to create this task:
       https://devcenter.heroku.com/articles/deploying-gradle-apps-on-heroku
       
       If you're stilling having trouble, please submit a ticket so we can help:
       https://help.heroku.com
       
       Thanks,
       Heroku
 !     Push rejected, failed to compile Gradle app.
 !     Push failed`

**Comment by TiboDeMunck** [comment]
The deployment on heroku should be of the api not the plugin.
https://github.com/TiboDeMunck/runelite-live-friend-locations-api

**Comment by 3st4ckz** [comment]
I'm an idiot. Thanks for the help!
